export const PASSWORD_CHANGE_ERROR = "PASSWORD_CHANGE_ERROR";
export const PASSWORD_CHANGE_SUCCESS = "PASSWORD_CHANGE_SUCCESS";
export const PASSWORD_CHANGE_BEGIN = "PASSWORD_CHANGE_BEGIN";
export const PASSWORD_CHANGE_COMPLETE = "PASSWORD_CHANGE_COMPLETE";

