export const ANOMALOUS_RULES_DATA_FETCH_BEGIN = "ANOMALOUS_RULES_DATA_FETCH_BEGIN";
export const ANOMALOUS_RULES_DATA_FETCH_SUCCESS = "ANOMALOUS_RULES_DATA_FETCH_SUCCESS";
export const ANOMALOUS_RULES_DATA_FETCH_ERROR = "ANOMALOUS_RULES_DATA_FETCH_ERROR";
export const ANOMALOUS_RULES_DATA_FETCH_COMPLETE = "ANOMALOUS_RULES_DATA_FETCH_COMPLETE";