export const ANOMALOUS_RULES_DATA_FETCH_BEGIN = "ANOMALOUS_RULES_DATA_FETCH_BEGIN";
export const ANOMALOUS_RULES_DATA_FETCH_SUCCESS = "ANOMALOUS_RULES_DATA_FETCH_SUCCESS";
export const ANOMALOUS_RULES_DATA_FETCH_ERROR = "ANOMALOUS_RULES_DATA_FETCH_ERROR";
export const ANOMALOUS_RULES_DATA_FETCH_COMPLETE = "ANOMALOUS_RULES_DATA_FETCH_COMPLETE";

export const ACCEPT_RULE_DRAWER_TOGGLE = "ACCEPT_RULE_DRAWER_TOGGLE";

export const CLOSE_ALL_DRAWER = "CLOSE_ALL_DRAWER";
export const RULE_SELECTED_TO_ACCEPT = "RULE_SELECTED_TO_ACCEPT";

export const ACCEPT_ANOMALOUS_RULE_BEGIN = "ACCEPT_ANOMALOUS_RULE_BEGIN";
export const ACCEPT_ANOMALOUS_RULE_SUCCESS = "ACCEPT_ANOMALOUS_RULE_SUCCESS";
export const ACCEPT_ANOMALOUS_RULE_COMPLETE = "ACCEPT_ANOMALOUS_RULE_COMPELTE";
export const ACCEPT_ANOMALOUS_RULE_ERROR = "ACCEPT_ANOMALOUS_RULE_ERROR";

export const TOGGLE_FLAGGED_RULE_BEGIN = "TOGGLE_FLAGGED_RULE_BEGIN";
export const TOGGLE_FLAGGED_RULE_SUCCESS = "TOGGLE_FLAGGED_RULE_SUCCESS";
export const TOGGLE_FLAGGED_RULE_COMPLETE = "TOGGLE_FLAGGED_RULE_COMPLETE";
export const TOGGLE_FLAGGED_RULE_ERROR = "TOGGLE_FLAGGED_RULE_ERROR";

export const CLEAN_ALL_STATE = "CLEAN_ALL_STATE";

export const PAGINATION_UPDATE = "PAGINATION_UPDATE" 
export const UPDATE_PAGINATION_PAGE_COUNT = "UPDATE_PAGINATION_PAGE_COUNT"