export const DATE_RANGE_PICKER_FILTER_UPDATED = "DATE_RANGE_PICKER_FILTER_UPDATED";
export const FIREWALL_RULE_FILTER_UPDATED = "FIREWALL_RULE_FILTER_UPDATED";
export const APPLICATION_FILTER_UPDATED = "APPLICATION_FILTER_UPDATED";
export const PROTOCOL_FILTER_UPDATED  = "PROTOCOL_FILTER_UPDATED";
export const SOURCE_ZONE_FILTER_UPDATED = "SOURCE_ZONE_FILTER_UPDATED";
export const DESTINATION_ZONE_FILTER_UPDATED = "DESTINATION_ZONE_FILTER_UPDATED";
// export const IP_ADDRESS_FILTER_UPDATED = "IP_ADDRESS_FILTER_UPDATED"


