export const DATE_RANGE_FILTER_UPDATED = "DATE_RANGE_FILTER_UPDATED";
export const FIREWALL_RULE_FILTER_UPDATED = "FIREWALL_RULE_FILTER_UPDATED";
export const APPLICATION_FILTER_UPDATED = "APPLICATION_FILTER_UPDATED";

