export const MAP_CHART_LOADING = "MAP_CHART_LOADING"
export const MAP_CHART_DATA_FETCH_SUCCESS = "MAP_CHART_DATA_FETCH_SUCCESS"
export const MAP_CHART_DATA_FETCH_COMPLETE = "MAP_CHART_DATA_FETCH_COMPLETE"
export const MAP_CHART_ERROR = "MAP_CHART_ERROR"
export const UPDATE_MAP_CHART = "UPDATE_MAP_CHART"
export const COUNTRY_LIST_DATA_FETCH_SUCCESS = "COUNTRY_LIST_DATA_FETCH_SUCCESS"
export const COUNTRY_LIST_DATA_FETCH_COMPLETE = "COUNTRY_LIST_DATA_FETCH_COMPLETE"
export const COUNTRY_LIST_DATA_FETCH_ERROR = "COUNTRY_LIST_DATA_FETCH_ERROR"

