export const UNVERIFIED_RULES_DATA_FETCH_BEGIN = "UNVERIFIED_RULES_DATA_FETCH_BEGIN";
export const UNVERIFIED_RULES_DATA_FETCH_SUCCESS = "UNVERIFIED_RULES_DATA_FETCH_SUCCESS";
export const UNVERIFIED_RULES_DATA_FETCH_ERROR = "UNVERIFIED_RULES_DATA_FETCH_ERROR";
export const UNVERIFIED_RULES_DATA_FETCH_COMPLETE = "UNVERIFIED_RULES_DATA_FETCH_COMPLETE";

export const ACCEPT_RULE_DRAWER_TOGGLE = "ACCEPT_RULE_DRAWER_TOGGLE";
export const REJECT_RULE_DRAWER_TOGGLE = "REJECT_RULE_DRAWER_TOGGLE";
export const UPDATE_RULE_DRAWER_TOGGLE = "UPDATE_RULE_DRAWER_TOGGLE";

export const CLOSE_ALL_DRAWER = "CLOSE_ALL_DRAWER";
export const RULE_SELECTED_TO_ACCEPT = "RULE_SELECTED_TO_ACCEPT";
export const RULE_SELECTED_TO_REJECT = "RULE_SELECTED_TO_REJECT";
export const RULE_SELECTED_TO_UPDATE = "RULE_SELECTED_TO_UPDATE";

export const ACCEPT_UNVERFIED_RULE_BEGIN = "ACCEPT_UNVERFIED_RULE_BEGIN";
export const ACCEPT_UNVERFIED_RULE_SUCCESS = "ACCEPT_UNVERFIED_RULE_SUCCESS";
export const ACCEPT_UNVERFIED_RULE_COMPLETE = "ACCEPT_UNVERFIED_RULE_COMPELTE";
export const ACCEPT_UNVERFIED_RULE_ERROR = "ACCEPT_UNVERFIED_RULE_ERROR";


export const REJECT_UNVERFIED_RULE_BEGIN = "REJECT_UNVERFIED_RULE_BEGIN";
export const REJECT_UNVERFIED_RULE_SUCCESS = "REJECT_UNVERFIED_RULE_SUCCESS";
export const REJECT_UNVERFIED_RULE_COMPLETE = "REJECT_UNVERFIED_RULE_COMPLETE";
export const REJECT_UNVERFIED_RULE_ERROR = "REJECT_UNVERFIED_RULE_ERROR";


export const UPDATE_UNVERFIED_RULE_BEGIN = "UDPATE_UNVERFIED_RULE_BEGIN";
export const UPDATE_UNVERFIED_RULE_SUCCESS = "UPDATE_UNVERFIED_RULE_SUCCESS";
export const UPDATE_UNVERFIED_RULE_COMPLETE = "UPDATE_UNVERFIED_RULE_COMPLETE";
export const UPDATE_UNVERFIED_RULE_ERROR = "UPDATE_UNVERFIED_RULE_ERROR";

export const CLEAN_ALL_STATE = "CLEAN_ALL_STATE";

export const PAGINATION_UPDATE = "PAGINATION_UPDATE" 
export const UPDATE_PAGINATION_PAGE_COUNT = "UPDATE_PAGINATION_PAGE_COUNT"