export const UNVERIFIED_RULES_DATA_FETCH_BEGIN = "UNVERIFIED_RULES_DATA_FETCH_BEGIN";
export const UNVERIFIED_RULES_DATA_FETCH_SUCCESS = "UNVERIFIED_RULES_DATA_FETCH_SUCCESS";
export const UNVERIFIED_RULES_DATA_FETCH_ERROR = "UNVERIFIED_RULES_DATA_FETCH_ERROR";
export const UNVERIFIED_RULES_DATA_FETCH_COMPLETE = "UNVERIFIED_RULES_DATA_FETCH_COMPLETE";
export const ACCEPT_RULE_DRAWER_TOGGLE = "ACCEPT_RULE_DRAWER_TOGGLE";
export const CLOSE_ALL_DRAWER = "CLOSE_ALL_DRAWER";
export const RULE_SELECTED_TO_ACCEPT = "RULE_SELECTED_TO_ACCEPT";
export const RULE_SELECTED_TO_REJECT = "RULE_SELECTED_TO_REJECT";
export const RULE_SELECTED_TO_UPDATE = "RULE_SELECTED_TO_UPDATE";
export const ACCEPT_UNVERFIED_RULE_BEGIN = "ACCEPT_UNVERFIED_RULE_BEGIN";
export const ACCEPT_UNVERFIED_RULE_SUCCESS = "ACCEPT_UNVERFIED_RULE_SUCCESS";
export const ACCEPT_UNVERFIED_RULE_COMPLETE = "ACCEPT_UNVERFIED_RULE_COMPELTE";
export const ACCEPT_UNVERFIED_RULE_ERROR = "ACCEPT_UNVERFIED_RULE_ERROR";



