export const VERIFIED_RULES_DATA_FETCH_BEGIN = "VERIFIED_RULES_DATA_FETCH_BEGIN";
export const VERIFIED_RULES_DATA_FETCH_SUCCESS = "VERIFIED_RULES_DATA_FETCH_SUCCESS";
export const VERIFIED_RULES_DATA_FETCH_ERROR = "VERIFIED_RULES_DATA_FETCH_ERROR";
export const VERIFIED_RULES_DATA_FETCH_COMPLETE = "VERIFIED_RULES_DATA_FETCH_COMPLETE";

export const PAGINATION_UPDATE = "PAGINATION_UPDATE" 
export const UPDATE_PAGINATION_PAGE_COUNT = "UPDATE_PAGINATION_PAGE_COUNT"