features_list = ['Receive Time',
                 'Rule',
                 'Source address',
                 'Destination address',
                 'Application',
                 'Source Zone',
                 'Source Port',
                 'Destination Port',
                 'IP Protocol',
                 'Repeat Count',
                 'Category',
                 'Action',
                 'Bytes Sent',
                 'Bytes Received',
                 'Session End Reason',
                 'Packets Sent',
                 'Elapsed Time (sec)',
                 'Packets Received']
