# Generated by Django 2.2.8 on 2020-01-21 02:42

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
            ],
        ),
        migrations.CreateModel(
            name='TrafficLogs',
            fields=[
            ],
        ),
    ]
