# Generated by Django 2.2.8 on 2020-01-21 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casdb', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExampleModel',
        ),
    ]
