# Generated by Django 2.2.5 on 2019-12-19 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficLogs',
            fields=[
            ],
        ),
    ]
