# Generated by Django 2.2.5 on 2019-11-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='verified_date_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
