# Generated by Django 2.2.5 on 2020-05-13 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0002_auto_20200513_0004'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rule',
            table='fh_prd_trfc_rule_f',
        ),
    ]
