# Generated by Django 2.2.5 on 2020-05-13 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0003_auto_20200513_1039'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rule',
            table=None,
        ),
    ]
