# Generated by Django 2.2.5 on 2019-11-12 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ipaddress_alias'),
        ('rules', '0004_auto_20191112_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rule',
            old_name='rule_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='rule',
            old_name='rule_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='tenant',
        ),
        migrations.AddField(
            model_name='rule',
            name='firewall_rule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.FirewallRule'),
        ),
    ]
