# Generated by Django 2.2.8 on 2020-05-14 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0005_trafficrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficrule',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rules.TrafficRule'),
        ),
    ]
