# Generated by Django 2.2.5 on 2019-11-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0005_auto_20191112_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='is_anomalous_rule',
            field=models.BooleanField(default=False),
        ),
    ]
