# Generated by Django 2.2.5 on 2019-11-15 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0006_rule_is_anomalous_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Application'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='destination_ip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules_destination_ip', to='core.IPAddress'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='source_ip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules_source_ip', to='core.IPAddress'),
        ),
    ]
