# Generated by Django 2.2.8 on 2020-05-15 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('troubleticket', '0003_auto_20200515_0106'),
        ('rules', '0007_trafficrule_is_generic'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagetrafficrule',
            name='is_generic',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='stagetrafficrule',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rules.StageTrafficRule'),
        ),
        migrations.DeleteModel(
            name='Rule',
        ),
    ]
