# Generated by Django 2.2.5 on 2019-11-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0008_auto_20191115_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
