# Generated by Django 2.2.8 on 2020-05-15 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0008_auto_20200515_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagetrafficrule',
            name='parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rules.StageTrafficRule'),
        ),
        migrations.AlterField(
            model_name='trafficrule',
            name='firewall_rule',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.FirewallRule'),
        ),
    ]
