# Generated by Django 2.2.8 on 2020-05-13 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('log_name', models.CharField(max_length=500, null=True)),
                ('batch_type', models.CharField(max_length=100, null=True)),
                ('batch_sub_type', models.CharField(max_length=200, null=True)),
                ('message', models.CharField(max_length=500, null=True)),
                ('exit_message', models.CharField(max_length=1000, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('end_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
