# Generated by Django 2.2.5 on 2020-01-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('log_name', models.CharField(max_length=500)),
                ('batch_type', models.CharField(max_length=100)),
                ('batch_sub_type', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=500)),
                ('exit_message', models.CharField(max_length=1000)),
                ('state', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('end_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
