# Generated by Django 2.2.5 on 2020-01-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='batch_sub_type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='batch_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='end_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='exit_message',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='log_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='message',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
