# Generated by Django 2.2.8 on 2020-05-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troubleticket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='troubleticketrule',
            name='rule',
        ),
        migrations.AddField(
            model_name='troubleticketanomaly',
            name='is_anomaly',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='troubleticketanomaly',
            name='severity_level',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='TroubleTicketAnomalyTrafficLog',
        ),
        migrations.DeleteModel(
            name='TroubleTicketRule',
        ),
    ]
