# Generated by Django 2.2.5 on 2019-11-05 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('troubleticket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='troubleticketfollowup',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='troubleticketfollowup',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='troubleticketfollowup',
            name='trouble_ticket',
        ),
        migrations.RenameField(
            model_name='troubleticketanomaly',
            old_name='log_record_number',
            new_name='row_number',
        ),
        migrations.RemoveField(
            model_name='troubleticketanomaly',
            name='destination_ip',
        ),
        migrations.RemoveField(
            model_name='troubleticketanomaly',
            name='destination_port',
        ),
        migrations.RemoveField(
            model_name='troubleticketanomaly',
            name='source_ip',
        ),
        migrations.RemoveField(
            model_name='troubleticketanomaly',
            name='source_port',
        ),
        migrations.AlterField(
            model_name='troubleticketfollowupanomaly',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='troubleticketfollowupanomaly',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='TroubleTicket',
        ),
        migrations.DeleteModel(
            name='TroubleTicketFollowUp',
        ),
        migrations.DeleteModel(
            name='TroubleTicketType',
        ),
    ]
