# Generated by Django 2.2.5 on 2019-10-20 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('troubleticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='troubleticketfollowup',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='troubleticketfollowup',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='troubleticketfollowup',
            name='trouble_ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='troubleticket.TroubleTicket'),
        ),
        migrations.AddField(
            model_name='troubleticket',
            name='created_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='troubleticket',
            name='trouble_ticket_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='troubleticket.TroubleTicketType'),
        ),
    ]
