# Generated by Django 2.2.5 on 2019-11-05 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('troubleticket', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='troubleticketfollowupanomaly',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='troubleticketfollowupanomaly',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='troubleticketfollowupanomaly',
            name='trouble_ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='troubleticket.TroubleTicketAnomaly'),
        ),
        migrations.AddField(
            model_name='troubleticketanomaly',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TrafficLog'),
        ),
    ]
