# Generated by Django 2.2.5 on 2019-11-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troubleticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='troubleticketanomaly',
            name='application',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='troubleticketanomaly',
            name='bytes_received',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='troubleticketanomaly',
            name='bytes_sent',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
