# Generated by Django 2.2.8 on 2020-01-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troubleticket', '0002_auto_20200121_0242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='troubleticketanomaly',
            name='row_number',
        ),
        migrations.AddField(
            model_name='troubleticketanomaly',
            name='action',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='troubleticketanomaly',
            name='application',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='troubleticketanomaly',
            name='bytes_received',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='troubleticketanomaly',
            name='bytes_sent',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='troubleticketanomaly',
            name='category',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='troubleticketanomaly',
            name='destination_ip',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='troubleticketanomaly',
            name='destination_port',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='troubleticketanomaly',
            name='destination_zone',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='troubleticketanomaly',
            name='packets_received',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='troubleticketanomaly',
            name='packets_sent',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='troubleticketanomaly',
            name='protocol',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='troubleticketanomaly',
            name='session_end_reason',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='troubleticketanomaly',
            name='source_ip',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='troubleticketanomaly',
            name='source_port',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='troubleticketanomaly',
            name='source_zone',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
