# Generated by Django 2.2.8 on 2020-06-15 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('troubleticket', '0002_auto_20200516_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='TroubleTicketGroupAnomaly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=500, null=True)),
                ('repeat_count', models.PositiveIntegerField(null=True)),
                ('time_elapsed', models.BigIntegerField(null=True)),
                ('reasons', models.CharField(max_length=500, null=True)),
                ('logged_datetime', models.DateTimeField(null=True)),
                ('threat_content_type', models.CharField(max_length=50, null=True)),
                ('source_address', models.CharField(max_length=50, null=True)),
                ('destination_address', models.CharField(max_length=50, null=True)),
                ('nat_source_ip', models.CharField(max_length=50, null=True)),
                ('nat_destination_ip', models.CharField(max_length=50, null=True)),
                ('destination_port', models.PositiveIntegerField(null=True)),
                ('source_port', models.PositiveIntegerField(null=True)),
                ('nat_destination_port', models.PositiveIntegerField(null=True)),
                ('application', models.CharField(max_length=250, null=True)),
                ('protocol', models.CharField(max_length=50, null=True)),
                ('log_action', models.CharField(max_length=50, null=True)),
                ('source_zone', models.CharField(max_length=250, null=True)),
                ('destination_zone', models.CharField(max_length=250, null=True)),
                ('inbound_interface', models.CharField(max_length=250, null=True)),
                ('outbound_interface', models.CharField(max_length=250, null=True)),
                ('action', models.CharField(max_length=250, null=True)),
                ('category', models.CharField(max_length=250, null=True)),
                ('session_end_reason', models.CharField(max_length=250, null=True)),
                ('source_country', models.CharField(max_length=3, null=True)),
                ('destination_country', models.CharField(max_length=3, null=True)),
                ('device_name', models.CharField(max_length=250, null=True)),
                ('flags', models.CharField(max_length=50, null=True)),
                ('vsys', models.CharField(max_length=50, null=True)),
                ('bytes_sent', models.BigIntegerField(null=True)),
                ('bytes_received', models.BigIntegerField(null=True)),
                ('packets_received', models.BigIntegerField(null=True)),
                ('packets_sent', models.BigIntegerField(null=True)),
                ('verified_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('is_anomaly', models.BooleanField(default=None, null=True)),
                ('severity_level', models.CharField(max_length=50, null=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grp_assg_to', to=settings.AUTH_USER_MODEL)),
                ('firewall_rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grp_frwl_rule', to='core.FirewallRule')),
                ('log', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grp_log', to='core.TrafficLog')),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grp_verified_by_tt', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fh_prd_tt_anmly_grp_f',
            },
        ),
    ]
