# Generated by Django 2.2.5 on 2019-11-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troubleticket', '0002_auto_20191105_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='troubleticketanomaly',
            name='bytes_received',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='troubleticketanomaly',
            name='bytes_sent',
            field=models.BigIntegerField(),
        ),
    ]
