# Generated by Django 2.2.8 on 2020-05-15 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('troubleticket', '0002_auto_20200513_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='troubleticketrule',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rules.TrafficRule'),
        ),
    ]
