# Generated by Django 2.2.5 on 2019-11-26 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('troubleticket', '0002_auto_20191124_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='troubleticketanomaly',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
