# Generated by Django 2.2.5 on 2019-10-24 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troubleticket', '0002_auto_20191020_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='troubletickettype',
            name='name',
            field=models.CharField(choices=[('AN', 'ANOMALY'), ('RU', 'RULE')], max_length=2),
        ),
    ]
