# Generated by Django 2.2.5 on 2019-11-08 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('troubleticket', '0002_auto_20191108_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='troubleticketanomaly',
            name='log',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.TrafficLog'),
        ),
        migrations.AlterField(
            model_name='troubleticketfollowupanomaly',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='troubleticketfollowupanomaly',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='troubleticketfollowupanomaly',
            name='trouble_ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='troubleticket.TroubleTicketAnomaly'),
        ),
    ]
