# Generated by Django 2.2.8 on 2020-01-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troubleticket', '0003_auto_20200127_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='troubleticketanomaly',
            name='repeat_count',
            field=models.IntegerField(default=0),
        ),
    ]
