# Generated by Django 2.2.5 on 2019-11-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troubleticket', '0003_troubleticketanomaly_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='troubleticketanomaly',
            name='reasons',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
