# Generated by Django 2.2.8 on 2020-06-21 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('troubleticket', '0004_troubleticketanomaly_tt_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagetroubleticketanomaly',
            name='tt_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='troubleticket.TroubleTicketGroupAnomaly'),
        ),
    ]
