# Generated by Django 2.2.5 on 2019-11-12 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ipaddress_alias'),
        ('troubleticket', '0004_troubleticketrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='troubleticketanomaly',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Tenant'),
        ),
    ]
