# Generated by Django 2.2.5 on 2019-11-12 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ipaddress_alias'),
        ('troubleticket', '0005_troubleticketanomaly_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='troubleticketanomaly',
            name='tenant',
        ),
        migrations.AddField(
            model_name='troubleticketanomaly',
            name='firewall_rule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.FirewallRule'),
        ),
    ]
