# Generated by Django 2.2.8 on 2020-01-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troubleticket', '0005_troubleticketanomaly_time_elapsed'),
    ]

    operations = [
        migrations.AddField(
            model_name='troubleticketanomaly',
            name='logged_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
