# Generated by Django 2.2.5 on 2019-11-19 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20191119_0350'),
        ('troubleticket', '0006_auto_20191112_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='TroubleTicketAnomalyTrafficLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.BigIntegerField()),
                ('log', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.TrafficLog')),
                ('ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='troubleticket.TroubleTicketAnomaly')),
            ],
        ),
    ]
