# Generated by Django 2.2.8 on 2020-01-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troubleticket', '0006_troubleticketanomaly_logged_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='troubleticketanomaly',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
