# Generated by Django 2.2.8 on 2020-01-30 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('troubleticket', '0007_troubleticketanomaly_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='troubleticketanomaly',
            name='verified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verified_by_tt', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='troubleticketanomaly',
            name='verified_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
