# Generated by Django 2.2.8 on 2020-01-30 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troubleticket', '0008_auto_20200130_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='troubleticketanomaly',
            name='verified_datetime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
