# Generated by Django 2.2.8 on 2020-01-04 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0014_backgroundjob_celerytaskmeta_celerytasksetmeta'),
    ]

    operations = [
        migrations.CreateModel(
            name='MISDailySourceIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('address', models.CharField(max_length=250)),
                ('tenant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.FirewallRule')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MISDailyDestinationIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('address', models.CharField(max_length=250)),
                ('tenant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.FirewallRule')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MISDailyApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('name', models.CharField(max_length=250)),
                ('tenant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.FirewallRule')),
            ],
        ),
    ]
