# Generated by Django 2.2.5 on 2020-01-04 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_backgroundjob_celerytaskmeta_celerytasksetmeta'),
        ('mis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MisDaily',
            fields=[
            ],
        ),
        migrations.CreateModel(
            name='MisDailyPerSourceDestinationPair',
            fields=[
            ],
        ),
        migrations.CreateModel(
            name='MisDailyRequestFromBlackListEvent',
            fields=[
            ],
        ),
        migrations.CreateModel(
            name='MisDailyResponseToBlackListEvent',
            fields=[
            ],
        ),
        migrations.RemoveField(
            model_name='misdailyapplication',
            name='date',
        ),
        migrations.RemoveField(
            model_name='misdailyapplication',
            name='id',
        ),
        migrations.RemoveField(
            model_name='misdailyapplication',
            name='name',
        ),
        migrations.RemoveField(
            model_name='misdailyapplication',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='misdailydestinationip',
            name='address',
        ),
        migrations.RemoveField(
            model_name='misdailydestinationip',
            name='date',
        ),
        migrations.RemoveField(
            model_name='misdailydestinationip',
            name='id',
        ),
        migrations.RemoveField(
            model_name='misdailydestinationip',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='misdailysourceip',
            name='address',
        ),
        migrations.RemoveField(
            model_name='misdailysourceip',
            name='date',
        ),
        migrations.RemoveField(
            model_name='misdailysourceip',
            name='id',
        ),
        migrations.RemoveField(
            model_name='misdailysourceip',
            name='tenant_id',
        ),
        migrations.CreateModel(
            name='DailySourceIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('address', models.CharField(max_length=250)),
                ('firewall_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.FirewallRule')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DailyResponseToBlackListEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_datetime', models.DateTimeField(null=True)),
                ('source_ip', models.CharField(max_length=250, null=True)),
                ('destination_ip', models.CharField(max_length=250, null=True)),
                ('application', models.CharField(max_length=250, null=True)),
                ('protocol', models.CharField(max_length=250, null=True)),
                ('source_zone', models.CharField(max_length=250, null=True)),
                ('destination_zone', models.CharField(max_length=250, null=True)),
                ('inbound_interface', models.CharField(max_length=250, null=True)),
                ('outbound_interface', models.CharField(max_length=250, null=True)),
                ('action', models.CharField(max_length=250, null=True)),
                ('category', models.CharField(max_length=250, null=True)),
                ('session_end_reason', models.CharField(max_length=250, null=True)),
                ('row_number', models.BigIntegerField()),
                ('source_port', models.PositiveIntegerField()),
                ('destination_port', models.PositiveIntegerField()),
                ('bytes_sent', models.BigIntegerField()),
                ('bytes_received', models.BigIntegerField()),
                ('repeat_count', models.PositiveIntegerField()),
                ('packets_received', models.BigIntegerField()),
                ('packets_sent', models.BigIntegerField()),
                ('time_elapsed', models.BigIntegerField()),
                ('firewall_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.FirewallRule')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DailyRequestFromBlackListEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_datetime', models.DateTimeField(null=True)),
                ('source_ip', models.CharField(max_length=250, null=True)),
                ('destination_ip', models.CharField(max_length=250, null=True)),
                ('application', models.CharField(max_length=250, null=True)),
                ('protocol', models.CharField(max_length=250, null=True)),
                ('source_zone', models.CharField(max_length=250, null=True)),
                ('destination_zone', models.CharField(max_length=250, null=True)),
                ('inbound_interface', models.CharField(max_length=250, null=True)),
                ('outbound_interface', models.CharField(max_length=250, null=True)),
                ('action', models.CharField(max_length=250, null=True)),
                ('category', models.CharField(max_length=250, null=True)),
                ('session_end_reason', models.CharField(max_length=250, null=True)),
                ('row_number', models.BigIntegerField()),
                ('source_port', models.PositiveIntegerField()),
                ('destination_port', models.PositiveIntegerField()),
                ('bytes_sent', models.BigIntegerField()),
                ('bytes_received', models.BigIntegerField()),
                ('repeat_count', models.PositiveIntegerField()),
                ('packets_received', models.BigIntegerField()),
                ('packets_sent', models.BigIntegerField()),
                ('time_elapsed', models.BigIntegerField()),
                ('firewall_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.FirewallRule')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DailyPerSourceDestinationPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_datetime', models.DateTimeField(null=True)),
                ('source_ip', models.CharField(max_length=250, null=True)),
                ('destination_ip', models.CharField(max_length=250, null=True)),
                ('destination_port', models.PositiveIntegerField()),
                ('avg_repeat_count', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sum_bytes_sent', models.BigIntegerField()),
                ('sum_bytes_received', models.BigIntegerField()),
                ('sum_packets_received', models.BigIntegerField()),
                ('sum_packets_sent', models.BigIntegerField()),
                ('sum_time_elapsed', models.BigIntegerField()),
                ('count_events', models.BigIntegerField()),
                ('firewall_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.FirewallRule')),
            ],
        ),
        migrations.CreateModel(
            name='DailyDestinationIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('address', models.CharField(max_length=250)),
                ('firewall_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.FirewallRule')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DailyApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('name', models.CharField(max_length=250)),
                ('firewall_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.FirewallRule')),
            ],
        ),
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('source_zone', models.CharField(max_length=250, null=True)),
                ('destination_zone', models.CharField(max_length=250, null=True)),
                ('application', models.CharField(max_length=250, null=True)),
                ('protocol', models.CharField(max_length=250, null=True)),
                ('avg_repeat_count', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sum_bytes_sent', models.BigIntegerField()),
                ('sum_bytes_received', models.BigIntegerField()),
                ('sum_packets_received', models.BigIntegerField()),
                ('sum_packets_sent', models.BigIntegerField()),
                ('sum_time_elapsed', models.BigIntegerField()),
                ('count_events', models.BigIntegerField()),
                ('firewall_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.FirewallRule')),
            ],
        ),
    ]
