# Generated by Django 2.2.8 on 2020-02-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrequestfromblacklistevent',
            name='bytes_received',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dailyrequestfromblacklistevent',
            name='bytes_sent',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dailyrequestfromblacklistevent',
            name='destination_port',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dailyrequestfromblacklistevent',
            name='packets_received',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dailyrequestfromblacklistevent',
            name='packets_sent',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dailyrequestfromblacklistevent',
            name='repeat_count',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dailyrequestfromblacklistevent',
            name='row_number',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dailyrequestfromblacklistevent',
            name='source_port',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dailyrequestfromblacklistevent',
            name='time_elapsed',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dailyresponsetoblacklistevent',
            name='bytes_received',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dailyresponsetoblacklistevent',
            name='bytes_sent',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dailyresponsetoblacklistevent',
            name='destination_port',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dailyresponsetoblacklistevent',
            name='packets_received',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dailyresponsetoblacklistevent',
            name='packets_sent',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dailyresponsetoblacklistevent',
            name='repeat_count',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dailyresponsetoblacklistevent',
            name='row_number',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dailyresponsetoblacklistevent',
            name='source_port',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dailyresponsetoblacklistevent',
            name='time_elapsed',
            field=models.BigIntegerField(null=True),
        ),
    ]
