# Generated by Django 2.2.5 on 2020-05-11 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200511_1800'),
        ('mis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficMisResponseToBlacklistedIPDaily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_datetime', models.DateTimeField(null=True)),
                ('processed_datetime', models.DateField(null=True)),
                ('source_address', models.CharField(max_length=250, null=True)),
                ('destination_address', models.CharField(max_length=250, null=True)),
                ('application', models.CharField(max_length=250, null=True)),
                ('protocol', models.CharField(max_length=250, null=True)),
                ('source_zone', models.CharField(max_length=250, null=True)),
                ('destination_zone', models.CharField(max_length=250, null=True)),
                ('inbound_interface', models.CharField(max_length=250, null=True)),
                ('outbound_interface', models.CharField(max_length=250, null=True)),
                ('action', models.CharField(max_length=250, null=True)),
                ('category', models.CharField(max_length=250, null=True)),
                ('session_end_reason', models.CharField(max_length=250, null=True)),
                ('destination_port', models.PositiveIntegerField(null=True)),
                ('avg_repeat_count', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sum_bytes_sent', models.BigIntegerField(default=0)),
                ('sum_bytes_received', models.BigIntegerField(default=0)),
                ('sum_packets_received', models.BigIntegerField(default=0)),
                ('sum_packets_sent', models.BigIntegerField(default=0)),
                ('sum_time_elapsed', models.BigIntegerField(default=0)),
                ('count_events', models.BigIntegerField(default=0)),
                ('firewall_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.FirewallRule')),
            ],
            options={
                'db_table': 'fh_prd_trfc_mis_res_to_blip_dy_a',
            },
        ),
        migrations.CreateModel(
            name='TrafficMisRequestFromBlacklistedIPDaily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_datetime', models.DateTimeField(null=True)),
                ('processed_datetime', models.DateField(null=True)),
                ('source_address', models.CharField(max_length=250, null=True)),
                ('destination_address', models.CharField(max_length=250, null=True)),
                ('application', models.CharField(max_length=250, null=True)),
                ('protocol', models.CharField(max_length=250, null=True)),
                ('source_zone', models.CharField(max_length=250, null=True)),
                ('destination_zone', models.CharField(max_length=250, null=True)),
                ('inbound_interface', models.CharField(max_length=250, null=True)),
                ('outbound_interface', models.CharField(max_length=250, null=True)),
                ('action', models.CharField(max_length=250, null=True)),
                ('category', models.CharField(max_length=250, null=True)),
                ('session_end_reason', models.CharField(max_length=250, null=True)),
                ('destination_port', models.PositiveIntegerField(null=True)),
                ('avg_repeat_count', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sum_bytes_sent', models.BigIntegerField(default=0)),
                ('sum_bytes_received', models.BigIntegerField(default=0)),
                ('sum_packets_received', models.BigIntegerField(default=0)),
                ('sum_packets_sent', models.BigIntegerField(default=0)),
                ('sum_time_elapsed', models.BigIntegerField(default=0)),
                ('count_events', models.BigIntegerField(default=0)),
                ('firewall_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.FirewallRule')),
            ],
            options={
                'db_table': 'fh_prd_trfc_mis_req_frm_blip_dy_a',
            },
        ),
        migrations.CreateModel(
            name='TrafficMisNewSourceIPDaily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_datetime', models.DateField(null=True)),
                ('processed_datetime', models.DateField(null=True)),
                ('alias', models.CharField(max_length=250, null=True)),
                ('source_address', models.CharField(max_length=250)),
                ('avg_repeat_count', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sum_bytes_sent', models.BigIntegerField()),
                ('sum_bytes_received', models.BigIntegerField()),
                ('sum_packets_received', models.BigIntegerField()),
                ('sum_packets_sent', models.BigIntegerField()),
                ('sum_time_elapsed', models.BigIntegerField()),
                ('count_events', models.BigIntegerField()),
                ('firewall_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.FirewallRule')),
            ],
            options={
                'db_table': 'fh_prd_trfc_mis_new_src_ip_dy_a',
            },
        ),
        migrations.CreateModel(
            name='TrafficMisNewDestinationIPDaily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_datetime', models.DateField(null=True)),
                ('processed_datetime', models.DateField(null=True)),
                ('alias', models.CharField(max_length=250, null=True)),
                ('destination_address', models.CharField(max_length=250)),
                ('avg_repeat_count', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sum_bytes_sent', models.BigIntegerField()),
                ('sum_bytes_received', models.BigIntegerField()),
                ('sum_packets_received', models.BigIntegerField()),
                ('sum_packets_sent', models.BigIntegerField()),
                ('sum_time_elapsed', models.BigIntegerField()),
                ('count_events', models.BigIntegerField()),
                ('firewall_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.FirewallRule')),
            ],
            options={
                'db_table': 'fh_prd_trfc_mis_new_dst_ip_dy_a',
            },
        ),
        migrations.CreateModel(
            name='TrafficMisNewApplicationDaily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_datetime', models.DateField(null=True)),
                ('processed_datetime', models.DateField(null=True)),
                ('application', models.CharField(max_length=250)),
                ('avg_repeat_count', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sum_bytes_sent', models.BigIntegerField()),
                ('sum_bytes_received', models.BigIntegerField()),
                ('sum_packets_received', models.BigIntegerField()),
                ('sum_packets_sent', models.BigIntegerField()),
                ('sum_time_elapsed', models.BigIntegerField()),
                ('count_events', models.BigIntegerField()),
                ('firewall_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.FirewallRule')),
            ],
            options={
                'db_table': 'fh_prd_trfc_mis_new_app_dy_a',
            },
        ),
    ]
