# Generated by Django 2.2.8 on 2020-05-16 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0002_auto_20200516_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyapplication',
            name='firewall_rule',
        ),
        migrations.RemoveField(
            model_name='dailypersourcedestinationpair',
            name='firewall_rule',
        ),
        migrations.RemoveField(
            model_name='dailyrequestfromblacklistevent',
            name='firewall_rule',
        ),
        migrations.RemoveField(
            model_name='dailyresponsetoblacklistevent',
            name='firewall_rule',
        ),
        migrations.DeleteModel(
            name='MisDaily',
        ),
        migrations.DeleteModel(
            name='MisDailyApplication',
        ),
        migrations.DeleteModel(
            name='MisDailyDestinationIP',
        ),
        migrations.DeleteModel(
            name='MisDailyPerSourceDestinationPair',
        ),
        migrations.DeleteModel(
            name='MisDailyRequestFromBlackListEvent',
        ),
        migrations.DeleteModel(
            name='MisDailyResponseToBlackListEvent',
        ),
        migrations.DeleteModel(
            name='MisDailySourceIP',
        ),
        migrations.DeleteModel(
            name='DailyApplication',
        ),
        migrations.DeleteModel(
            name='DailyPerSourceDestinationPair',
        ),
        migrations.DeleteModel(
            name='DailyRequestFromBlackListEvent',
        ),
        migrations.DeleteModel(
            name='DailyResponseToBlackListEvent',
        ),
    ]
