# Generated by Django 2.2.5 on 2020-01-10 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0002_auto_20200104_0900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daily',
            old_name='date',
            new_name='logged_datetime',
        ),
        migrations.RenameField(
            model_name='dailyapplication',
            old_name='date',
            new_name='logged_datetime',
        ),
        migrations.RenameField(
            model_name='dailydestinationip',
            old_name='date',
            new_name='logged_datetime',
        ),
        migrations.RenameField(
            model_name='dailysourceip',
            old_name='date',
            new_name='logged_datetime',
        ),
    ]
