# Generated by Django 2.2.5 on 2020-01-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0003_auto_20200110_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyapplication',
            old_name='name',
            new_name='application_name',
        ),
        migrations.RenameField(
            model_name='dailydestinationip',
            old_name='address',
            new_name='source_address',
        ),
        migrations.RenameField(
            model_name='dailysourceip',
            old_name='address',
            new_name='source_address',
        ),
        migrations.AddField(
            model_name='daily',
            name='processed_datetime',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='dailyapplication',
            name='processed_datetime',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='dailydestinationip',
            name='processed_datetime',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='dailypersourcedestinationpair',
            name='processed_datetime',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='dailyrequestfromblacklistevent',
            name='processed_datetime',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='dailyresponsetoblacklistevent',
            name='processed_datetime',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='dailysourceip',
            name='processed_datetime',
            field=models.DateField(null=True),
        ),
    ]
