# Generated by Django 2.2.5 on 2020-04-17 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20200226_1323'),
        ('mis', '0003_auto_20200208_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageTrafficMisNewSourceIPDaily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_datetime', models.DateField(null=True)),
                ('processed_datetime', models.DateField(null=True)),
                ('alias', models.CharField(max_length=250, null=True)),
                ('source_address', models.CharField(max_length=250)),
                ('avg_repeat_count', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sum_bytes_sent', models.BigIntegerField()),
                ('sum_bytes_received', models.BigIntegerField()),
                ('sum_packets_received', models.BigIntegerField()),
                ('sum_packets_sent', models.BigIntegerField()),
                ('sum_time_elapsed', models.BigIntegerField()),
                ('count_events', models.BigIntegerField()),
                ('firewall_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.FirewallRule')),
            ],
            options={
                'db_table': 'FH_STG_TRFC_MIS_NEW_SRC_IP_DY_A',
            },
        ),
    ]
