# Generated by Django 2.2.8 on 2020-01-18 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0004_auto_20200113_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailydestinationip',
            old_name='source_address',
            new_name='destination_address',
        ),
    ]
