# Generated by Django 2.2.5 on 2020-04-17 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0004_stagetrafficmisnewsourceipdaily'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stagetrafficmisnewsourceipdaily',
            table='fh_stg_trfc_mis_new_src_ip_dy_a',
        ),
    ]
