# Generated by Django 2.2.5 on 2020-04-17 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0006_stagetrafficmisnewapplicationdaily_stagetrafficmisnewdestinationipdaily'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stagetrafficmisnewapplicationdaily',
            old_name='application_name',
            new_name='application',
        ),
    ]
