# Generated by Django 2.2.5 on 2020-04-17 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20200226_1323'),
        ('mis', '0007_auto_20200417_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageTrafficMisResponseToBlacklistedIPDaily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_datetime', models.DateTimeField(null=True)),
                ('processed_datetime', models.DateField(null=True)),
                ('source_address', models.CharField(max_length=250, null=True)),
                ('destination_address', models.CharField(max_length=250, null=True)),
                ('application', models.CharField(max_length=250, null=True)),
                ('protocol', models.CharField(max_length=250, null=True)),
                ('source_zone', models.CharField(max_length=250, null=True)),
                ('destination_zone', models.CharField(max_length=250, null=True)),
                ('inbound_interface', models.CharField(max_length=250, null=True)),
                ('outbound_interface', models.CharField(max_length=250, null=True)),
                ('action', models.CharField(max_length=250, null=True)),
                ('category', models.CharField(max_length=250, null=True)),
                ('session_end_reason', models.CharField(max_length=250, null=True)),
                ('source_port', models.PositiveIntegerField(null=True)),
                ('destination_port', models.PositiveIntegerField(null=True)),
                ('bytes_sent', models.BigIntegerField(null=True)),
                ('bytes_received', models.BigIntegerField(null=True)),
                ('repeat_count', models.PositiveIntegerField(null=True)),
                ('packets_received', models.BigIntegerField(null=True)),
                ('packets_sent', models.BigIntegerField(null=True)),
                ('time_elapsed', models.BigIntegerField(null=True)),
                ('firewall_rule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.FirewallRule')),
            ],
            options={
                'db_table': 'fh_stg_trfc_mis_res_to_blip_dy_a',
            },
        ),
        migrations.CreateModel(
            name='StageTrafficMisRequestFromBlacklistedIPDaily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_datetime', models.DateTimeField(null=True)),
                ('processed_datetime', models.DateField(null=True)),
                ('source_address', models.CharField(max_length=250, null=True)),
                ('destination_address', models.CharField(max_length=250, null=True)),
                ('application', models.CharField(max_length=250, null=True)),
                ('protocol', models.CharField(max_length=250, null=True)),
                ('source_zone', models.CharField(max_length=250, null=True)),
                ('destination_zone', models.CharField(max_length=250, null=True)),
                ('inbound_interface', models.CharField(max_length=250, null=True)),
                ('outbound_interface', models.CharField(max_length=250, null=True)),
                ('action', models.CharField(max_length=250, null=True)),
                ('category', models.CharField(max_length=250, null=True)),
                ('session_end_reason', models.CharField(max_length=250, null=True)),
                ('source_port', models.PositiveIntegerField(null=True)),
                ('destination_port', models.PositiveIntegerField(null=True)),
                ('bytes_sent', models.BigIntegerField(null=True)),
                ('bytes_received', models.BigIntegerField(null=True)),
                ('repeat_count', models.PositiveIntegerField(null=True)),
                ('packets_received', models.BigIntegerField(null=True)),
                ('packets_sent', models.BigIntegerField(null=True)),
                ('time_elapsed', models.BigIntegerField(null=True)),
                ('firewall_rule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.FirewallRule')),
            ],
            options={
                'db_table': 'fh_stg_trfc_mis_req_frm_blip_dy_a',
            },
        ),
    ]
