# Generated by Django 2.2.5 on 2020-04-17 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0009_auto_20200417_2041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stagetrafficmisrequestfromblacklistedipdaily',
            old_name='firewall_rule_id',
            new_name='firewall_rule',
        ),
        migrations.RenameField(
            model_name='stagetrafficmisresponsetoblacklistedipdaily',
            old_name='firewall_rule_id',
            new_name='firewall_rule',
        ),
    ]
