# Generated by Django 2.2.5 on 2020-04-19 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_threatlogdetailevent'),
        ('mis', '0010_auto_20200417_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageTrafficMisDaily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_datetime', models.DateField(null=True)),
                ('processed_datetime', models.DateField(null=True)),
                ('source_zone', models.CharField(max_length=250, null=True)),
                ('destination_zone', models.CharField(max_length=250, null=True)),
                ('application', models.CharField(max_length=250, null=True)),
                ('protocol', models.CharField(max_length=250, null=True)),
                ('avg_repeat_count', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sum_bytes_sent', models.BigIntegerField()),
                ('sum_bytes_received', models.BigIntegerField()),
                ('sum_packets_received', models.BigIntegerField()),
                ('sum_packets_sent', models.BigIntegerField()),
                ('sum_time_elapsed', models.BigIntegerField()),
                ('count_events', models.BigIntegerField()),
                ('firewall_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.FirewallRule')),
            ],
            options={
                'db_table': 'fh_stg_trfc_mis_dy_a',
            },
        ),
    ]
