# Generated by Django 2.2.5 on 2020-04-19 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_threatlogdetailevent'),
        ('mis', '0011_stagetrafficmisdaily'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Daily',
            new_name='TrafficMisDaily',
        ),
        migrations.AlterModelTable(
            name='trafficmisdaily',
            table='fh_prd_trfc_mis_dy_a',
        ),
    ]
