# Generated by Django 2.2.5 on 2019-11-05 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191105_0858'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foxhounduser',
            name='tenant_id',
        ),
        migrations.AddField(
            model_name='foxhounduser',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Tenant'),
        ),
    ]
