# Generated by Django 2.2.5 on 2019-11-08 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FirewallRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=15)),
                ('type', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TrafficLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed_datetime', models.DateField(auto_now_add=True)),
                ('log_date', models.DateField()),
                ('log_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='VirtualSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TrafficLogDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.BigIntegerField()),
                ('source_port', models.PositiveIntegerField()),
                ('destination_port', models.PositiveIntegerField()),
                ('bytes_sent', models.BigIntegerField()),
                ('bytes_received', models.BigIntegerField()),
                ('repeat_count', models.PositiveIntegerField()),
                ('packets_received', models.BigIntegerField()),
                ('packets_sent', models.BigIntegerField()),
                ('time_elapsed', models.BigIntegerField()),
                ('logged_datetime', models.DateTimeField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='core.Application')),
                ('destination_ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_ip', to='core.IPAddress')),
                ('destination_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_zone', to='core.Zone')),
                ('firewall_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firewall_rule', to='core.FirewallRule')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocol', to='core.Protocol')),
                ('source_ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_ip', to='core.IPAddress')),
                ('source_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_zone', to='core.Zone')),
                ('traffic_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TrafficLog')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('virtual_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.VirtualSystem')),
            ],
        ),
        migrations.CreateModel(
            name='FirewallRuleZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firewall_destination_zone', to='core.Zone')),
                ('firewall_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.FirewallRule')),
                ('source_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firewall_source_zone', to='core.Zone')),
            ],
        ),
        migrations.AddField(
            model_name='firewallrule',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Tenant'),
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=250)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('iso_code', models.CharField(max_length=5)),
                ('ip_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.IPAddress')),
            ],
        ),
    ]
