# Generated by Django 2.2.5 on 2019-10-17 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networktopologydetails',
            name='network_topology',
        ),
        migrations.RemoveField(
            model_name='networktopologydetails',
            name='parent_device',
        ),
        migrations.RemoveField(
            model_name='ruledictionarymis',
            name='rule_dictionary',
        ),
        migrations.RemoveField(
            model_name='timeseriesbytes',
            name='processed_log',
        ),
        migrations.RemoveField(
            model_name='timeseriesbytes',
            name='virtual_system',
        ),
        migrations.DeleteModel(
            name='NetworkTopology',
        ),
        migrations.DeleteModel(
            name='NetworkTopologyDetails',
        ),
        migrations.DeleteModel(
            name='RuleDictionaryMIS',
        ),
        migrations.DeleteModel(
            name='TimeSeriesBytes',
        ),
    ]
