# Generated by Django 2.2.8 on 2020-01-21 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stagingfilter',
            old_name='destination_zone',
            new_name='destination_zone_id',
        ),
        migrations.RenameField(
            model_name='stagingfilter',
            old_name='source_zone',
            new_name='source_zone_id',
        ),
    ]
