# Generated by Django 2.2.5 on 2019-11-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficlogdetail',
            name='logged_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
