# Generated by Django 2.2.5 on 2019-11-05 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firewallrule',
            name='tenant',
        ),
        migrations.AddField(
            model_name='tenant',
            name='rule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.FirewallRule'),
        ),
    ]
