# Generated by Django 2.2.8 on 2020-05-16 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='threatlogdetail',
            old_name='destination_ip',
            new_name='destination_address',
        ),
        migrations.RenameField(
            model_name='threatlogdetail',
            old_name='source_ip',
            new_name='source_address',
        ),
        migrations.RenameField(
            model_name='trafficlogdetailgranularhour',
            old_name='destination_ip',
            new_name='destination_address',
        ),
        migrations.RenameField(
            model_name='trafficlogdetailgranularhour',
            old_name='source_ip',
            new_name='source_address',
        ),
        migrations.RemoveField(
            model_name='trafficlogdetail',
            name='destination_ip',
        ),
        migrations.RemoveField(
            model_name='trafficlogdetail',
            name='source_ip',
        ),
        migrations.AddField(
            model_name='trafficlogdetail',
            name='destination_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_address', to='core.IPAddress'),
        ),
        migrations.AddField(
            model_name='trafficlogdetail',
            name='source_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_address', to='core.IPAddress'),
        ),
    ]
