# Generated by Django 2.2.5 on 2019-11-05 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=50)),
                ('country_iso_code', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='FirewallRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('domain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Domain')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('src', 'Source'), ('dst', 'Destination')], max_length=3)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Tenant')),
            ],
        ),
        migrations.DeleteModel(
            name='IPCountry',
        ),
        migrations.RemoveField(
            model_name='virtualsystem',
            name='domain_code',
        ),
        migrations.RemoveField(
            model_name='virtualsystem',
            name='domain_url',
        ),
        migrations.RemoveField(
            model_name='virtualsystem',
            name='tenant_name',
        ),
        migrations.AddField(
            model_name='trafficlogdetail',
            name='row_number',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trafficlogdetail',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='core.Application'),
        ),
        migrations.AlterField(
            model_name='trafficlogdetail',
            name='destination_ip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_ip', to='core.IPAddress'),
        ),
        migrations.AlterField(
            model_name='trafficlogdetail',
            name='destination_zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_zone', to='core.Zone'),
        ),
        migrations.AlterField(
            model_name='trafficlogdetail',
            name='firewall_rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firewall_rule', to='core.FirewallRule'),
        ),
        migrations.AlterField(
            model_name='trafficlogdetail',
            name='protocol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocol', to='core.Protocol'),
        ),
        migrations.AlterField(
            model_name='trafficlogdetail',
            name='source_ip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_ip', to='core.IPAddress'),
        ),
        migrations.AlterField(
            model_name='trafficlogdetail',
            name='source_zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_zone', to='core.Zone'),
        ),
        migrations.DeleteModel(
            name='RuleDictionary',
        ),
        migrations.AddField(
            model_name='tenant',
            name='virtual_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.VirtualSystem'),
        ),
        migrations.AddField(
            model_name='firewallrule',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Tenant'),
        ),
        migrations.AddField(
            model_name='country',
            name='ip_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.IPAddress'),
        ),
    ]
