# Generated by Django 2.2.5 on 2020-05-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200511_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagetrafficlogdetaildaily',
            name='flags',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='stagetrafficlogdetailhourly',
            name='flags',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='trafficlogdetaildaily',
            name='flags',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='trafficlogdetailhourly',
            name='flags',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
