# Generated by Django 2.2.5 on 2019-11-24 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191124_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trafficlogdetailgranularhour',
            name='source_port',
        ),
    ]
