# Generated by Django 2.2.5 on 2020-05-14 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200513_2319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sankeychart',
            old_name='destination_ip',
            new_name='destination_address',
        ),
        migrations.RenameField(
            model_name='sankeychart',
            old_name='source_ip',
            new_name='source_address',
        ),
    ]
