# Generated by Django 2.2.5 on 2019-10-24 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191020_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficlog',
            name='log_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
