# Generated by Django 2.2.8 on 2020-01-21 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200121_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationchart',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Application'),
        ),
    ]
