# Generated by Django 2.2.5 on 2019-11-05 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191105_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='rule',
        ),
        migrations.AddField(
            model_name='firewallrule',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Tenant'),
            preserve_default=False,
        ),
    ]
