# Generated by Django 2.2.5 on 2019-10-17 10:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
