# Generated by Django 2.2.5 on 2019-11-13 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ipaddress_alias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipaddress',
            name='type',
        ),
    ]
