# Generated by Django 2.2.5 on 2019-10-18 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='ip_protocol',
            new_name='protocol',
        ),
    ]
