# Generated by Django 2.2.5 on 2019-11-05 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191105_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='tenant',
        ),
        migrations.AddField(
            model_name='zone',
            name='firewall_rule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.FirewallRule'),
            preserve_default=False,
        ),
    ]
