# Generated by Django 2.2.5 on 2019-12-01 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_trafficlogdetailgranularhour_source_port'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trafficlogdetailgranularhour',
            name='row_number',
        ),
    ]
