# Generated by Django 2.2.8 on 2020-01-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200121_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipchart',
            name='count',
            field=models.BigIntegerField(default=0),
        ),
    ]
