# Generated by Django 2.2.5 on 2019-10-18 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_log_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipdictionary',
            name='virtual_system',
        ),
        migrations.DeleteModel(
            name='ProcessedLog',
        ),
        migrations.DeleteModel(
            name='IPDictionary',
        ),
    ]
