# Generated by Django 2.2.5 on 2020-05-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200511_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagetrafficlogdetaildaily',
            name='count_events',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stagetrafficlogdetailhourly',
            name='count_events',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trafficlogdetaildaily',
            name='count_events',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trafficlogdetailhourly',
            name='count_events',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
