# Generated by Django 2.2.5 on 2019-12-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_trafficlogdetailgranularhour_row_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBLock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_rule_table_locked', models.BooleanField(default=False)),
            ],
        ),
    ]
