# Generated by Django 2.2.5 on 2019-11-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_zone_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='type',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
