# Generated by Django 2.2.5 on 2020-05-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200511_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagetrafficlogdetaildaily',
            name='device_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='stagetrafficlogdetaildaily',
            name='flags',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stagetrafficlogdetaildaily',
            name='vsys',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stagetrafficlogdetailhourly',
            name='device_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='stagetrafficlogdetailhourly',
            name='flags',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stagetrafficlogdetailhourly',
            name='vsys',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trafficlogdetaildaily',
            name='device_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='trafficlogdetaildaily',
            name='flags',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trafficlogdetaildaily',
            name='vsys',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trafficlogdetailhourly',
            name='device_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='trafficlogdetailhourly',
            name='flags',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trafficlogdetailhourly',
            name='vsys',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
