# Generated by Django 2.2.5 on 2019-12-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_dblock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dblock',
            old_name='is_rule_table_locked',
            new_name='is_locked',
        ),
        migrations.AddField(
            model_name='dblock',
            name='table_name',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
