# Generated by Django 2.2.5 on 2019-10-18 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191018_0325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='log',
            name='virtual_system',
        ),
        migrations.CreateModel(
            name='VirtualSystemDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('virtual_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.VirtualSystem')),
            ],
        ),
        migrations.AddField(
            model_name='log',
            name='virtual_system_date',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.VirtualSystemDate'),
        ),
    ]
