# Generated by Django 2.2.5 on 2020-01-24 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ipchart_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='celerytaskmeta',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='celerytasksetmeta',
            options={'managed': False},
        ),
    ]
