# Generated by Django 2.2.5 on 2019-10-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191018_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficlog',
            name='log_date',
            field=models.DateField(),
        ),
    ]
