# Generated by Django 2.2.5 on 2019-10-18 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191018_0359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='virtual_system_date',
        ),
        migrations.AddField(
            model_name='log',
            name='date_added',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='log',
            name='virtual_system',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.VirtualSystem'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='VirtualSystemDate',
        ),
    ]
