# Generated by Django 2.2.5 on 2019-11-06 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ipaddress_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firewallrule',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='firewall_rule',
        ),
        migrations.AddField(
            model_name='zone',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Tenant'),
            preserve_default=False,
        ),
    ]
