# Generated by Django 2.2.8 on 2020-01-24 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ipchart_count'),
        ('core', '0006_backgroundjob_celerytaskmeta_celerytasksetmeta'),
    ]

    operations = [
    ]
