# Generated by Django 2.2.5 on 2019-11-14 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tenantapplicationinfo_tenantipinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TenantIPInfo',
            new_name='TenantIPAddressInfo',
        ),
    ]
