# Generated by Django 2.2.5 on 2019-11-06 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191106_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='firewallrule',
            name='zone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Zone'),
            preserve_default=False,
        ),
    ]
