# Generated by Django 2.2.5 on 2019-10-18 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191018_0404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='destinaton_ip',
            new_name='destination_ip',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='destinaton_port',
            new_name='destination_port',
        ),
    ]
