# Generated by Django 2.2.5 on 2019-11-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191114_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantapplicationinfo',
            name='created_datetime',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantipaddressinfo',
            name='created_datetime',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
