# Generated by Django 2.2.5 on 2020-05-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='threatlog',
            name='bookmark',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='trafficlog',
            name='bookmark',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
