# Generated by Django 2.2.8 on 2020-01-27 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200125_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='SankeyChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bytes_sent', models.BigIntegerField()),
                ('bytes_received', models.BigIntegerField()),
                ('packets_sent', models.BigIntegerField()),
                ('packets_received', models.BigIntegerField()),
                ('count', models.BigIntegerField(default=0)),
                ('logged_datetime', models.DateTimeField()),
                ('source_ip', models.CharField(max_length=15)),
                ('destination_ip', models.CharField(max_length=15)),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Filter')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
