# Generated by Django 2.2.8 on 2019-12-06 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191203_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenantipaddressinfo',
            old_name='ip_address',
            new_name='address',
        ),
        migrations.AddField(
            model_name='tenantipaddressinfo',
            name='alias',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
