# Generated by Django 2.2.8 on 2020-01-29 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sankeychart'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='firewall_rule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.FirewallRule'),
        ),
    ]
