# Generated by Django 2.2.5 on 2020-05-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200512_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='log_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='threatlog',
            name='log_name',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='trafficlog',
            name='log_name',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
