# Generated by Django 2.2.5 on 2019-10-18 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191018_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
