# Generated by Django 2.2.5 on 2019-11-06 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_firewallrule_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firewallrule',
            name='zone',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='tenant',
        ),
        migrations.AddField(
            model_name='firewallrule',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Tenant'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FirewallRuleZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firewall_destination_zone', to='core.Zone')),
                ('firewall_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.FirewallRule')),
                ('source_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firewall_source_zone', to='core.Zone')),
            ],
        ),
    ]
