# Generated by Django 2.2.5 on 2019-10-18 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20191018_0423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='date_added',
            new_name='date',
        ),
    ]
