# Generated by Django 2.2.5 on 2019-11-07 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20191106_0435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trafficlog',
            name='tenant',
        ),
    ]
