# Generated by Django 2.2.8 on 2020-01-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_ipaddress_firewall_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficlog',
            name='chart_engine_ran',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='trafficlog',
            name='db_engine_ran',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='trafficlog',
            name='dc_engine_ran',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='trafficlog',
            name='mis_engine_ran',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='trafficlog',
            name='ml_engine_ran',
            field=models.BooleanField(null=True),
        ),
    ]
