# Generated by Django 2.2.5 on 2019-11-19 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20191114_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedLogDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_rows', models.IntegerField(default=0)),
                ('size', models.BigIntegerField(default=0)),
                ('firewall_rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.FirewallRule')),
                ('log', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.TrafficLog')),
            ],
        ),
    ]
