# Generated by Django 2.2.5 on 2020-05-12 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200512_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threatlog',
            name='bookmark',
        ),
        migrations.RemoveField(
            model_name='trafficlog',
            name='bookmark',
        ),
    ]
