# Generated by Django 2.2.8 on 2019-12-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_misdailydestinationip_misdailysourceip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='domain',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='firewallrule',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='misdailydestinationip',
            name='address',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='misdailysourceip',
            name='address',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='tenantapplicationinfo',
            name='application',
            field=models.CharField(max_length=250),
        ),
    ]
