# Generated by Django 2.2.5 on 2020-01-30 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200129_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficlogdetailgranularhour',
            name='firewall_rule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.FirewallRule'),
        ),
    ]
