# Generated by Django 2.2.5 on 2019-11-07 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_trafficlog_tenant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='country_iso_code',
            new_name='iso_code',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='country_name',
            new_name='name',
        ),
    ]
