# Generated by Django 2.2.8 on 2020-01-04 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_backgroundjob_celerytaskmeta_celerytasksetmeta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='misdailysourceip',
            name='tenant_id',
        ),
        migrations.AlterModelOptions(
            name='celerytaskmeta',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='celerytasksetmeta',
            options={'managed': True},
        ),
        migrations.DeleteModel(
            name='MISDailyDestinationIP',
        ),
        migrations.DeleteModel(
            name='MISDailySourceIP',
        ),
    ]
