# Generated by Django 2.2.8 on 2020-02-06 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200130_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedlogdetail',
            name='log',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
