# Generated by Django 2.2.5 on 2019-11-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20191119_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficlog',
            name='is_info_written',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='trafficlog',
            name='is_log_detail_written',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='trafficlog',
            name='is_rule_written',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
