# Generated by Django 2.2.8 on 2020-02-06 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200206_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processedlogdetail',
            old_name='n_rows',
            new_name='rows',
        ),
        migrations.RemoveField(
            model_name='processedlogdetail',
            name='size',
        ),
    ]
