# Generated by Django 2.2.8 on 2020-02-06 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200206_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedlogdetail',
            name='processed_date',
            field=models.DateField(null=True),
        ),
    ]
