# Generated by Django 2.2.5 on 2019-11-24 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20191124_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficlogdetail',
            name='action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action', to='core.Action'),
        ),
        migrations.AddField(
            model_name='trafficlogdetail',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='core.Category'),
        ),
        migrations.AddField(
            model_name='trafficlogdetail',
            name='inbound_interface',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inbound_interface', to='core.Interface'),
        ),
        migrations.AddField(
            model_name='trafficlogdetail',
            name='outbound_interface',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outbound_interface', to='core.Interface'),
        ),
        migrations.AddField(
            model_name='trafficlogdetail',
            name='session_end_reason',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_end_reason', to='core.SessionEndReason'),
        ),
        migrations.CreateModel(
            name='TrafficLogDetailGranularHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.BigIntegerField()),
                ('source_port', models.PositiveIntegerField()),
                ('destination_port', models.PositiveIntegerField()),
                ('bytes_sent', models.BigIntegerField()),
                ('bytes_received', models.BigIntegerField()),
                ('repeat_count', models.PositiveIntegerField()),
                ('packets_received', models.BigIntegerField()),
                ('packets_sent', models.BigIntegerField()),
                ('time_elapsed', models.BigIntegerField()),
                ('logged_datetime', models.DateTimeField()),
                ('action', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='granular_hour_action', to='core.Action')),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='granular_hour_application', to='core.Application')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='granular_hour_category', to='core.Category')),
                ('destination_ip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='granular_hour_destination_ip', to='core.IPAddress')),
                ('destination_zone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='granular_hour_destination_zone', to='core.Zone')),
                ('firewall_rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='granular_hour_firewall_rule', to='core.FirewallRule')),
                ('inbound_interface', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='granular_hour_inbound_interface', to='core.Interface')),
                ('outbound_interface', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='granular_hour_outbound_interface', to='core.Interface')),
                ('protocol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='granular_hour_protocol', to='core.Protocol')),
                ('session_end_reason', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='granular_hour_session_end_reason', to='core.SessionEndReason')),
                ('source_ip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='granular_hour_source_ip', to='core.IPAddress')),
                ('source_zone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='granular_hour_source_zone', to='core.Zone')),
                ('traffic_log', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.TrafficLog')),
            ],
        ),
    ]
