# Generated by Django 2.2.8 on 2020-01-13 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_backgroundjob_celerytaskmeta_celerytasksetmeta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firewall_rule', models.CharField(max_length=250)),
                ('logged_datetime', models.DateTimeField()),
                ('application', models.CharField(max_length=250)),
                ('bytes', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.CharField(max_length=250)),
                ('source_zone', models.CharField(max_length=250)),
                ('destination_zone', models.CharField(max_length=250)),
                ('firewall_rule', models.CharField(max_length=250)),
                ('protocol', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StagingFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.CharField(max_length=250)),
                ('source_zone', models.CharField(max_length=250)),
                ('destination_zone', models.CharField(max_length=250)),
                ('firewall_rule', models.CharField(max_length=250)),
                ('protocol', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSeriesChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firewall_rule', models.CharField(max_length=250)),
                ('logged_datetime', models.DateTimeField()),
                ('bytes_sent', models.BigIntegerField()),
                ('bytes_received', models.BigIntegerField()),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Filter')),
            ],
        ),
        migrations.CreateModel(
            name='RequestOriginChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firewall_rule', models.CharField(max_length=250)),
                ('country_name', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=10)),
                ('count', models.BigIntegerField()),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Filter')),
            ],
        ),
        migrations.CreateModel(
            name='IPChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firewall_rule', models.CharField(max_length=250)),
                ('logged_datetime', models.DateTimeField()),
                ('address', models.CharField(max_length=15)),
                ('bytes_sent', models.BigIntegerField()),
                ('bytes_received', models.BigIntegerField()),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Filter')),
            ],
        ),
    ]
