# Generated by Django 2.2.5 on 2020-02-08 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200206_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundjob',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_background_job', to='core.CeleryTaskmeta'),
        ),
    ]
