# Generated by Django 2.2.5 on 2019-11-24 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20191124_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficlog',
            name='is_granular_hour_written',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
