# Generated by Django 2.2.5 on 2020-01-15 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200113_1856'),
        ('core', '0016_auto_20200113_1646'),
    ]

    operations = [
    ]
