# Generated by Django 2.2.5 on 2020-02-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200208_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backgroundjob',
            name='task',
        ),
        migrations.AddField(
            model_name='backgroundjob',
            name='task_id',
            field=models.CharField(blank=True, max_length=155, null=True, unique=True),
        ),
    ]
