# Generated by Django 2.2.8 on 2020-01-18 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_merge_20200115_1513'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='celerytaskmeta',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='celerytasksetmeta',
            options={'managed': True},
        ),
    ]
