# Generated by Django 2.2.5 on 2020-02-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_threatlogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threatlogs',
            name='processed_datetime',
            field=models.DateTimeField(),
        ),
    ]
