# Generated by Django 2.2.5 on 2020-02-10 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200210_2137'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ThreatLogs',
        ),
    ]
