# Generated by Django 2.2.8 on 2020-02-18 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_threatlogs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProcessedLogDetail',
            new_name='ProcessedTrafficLogDetail',
        ),
        migrations.CreateModel(
            name='ProcessedThreatLogDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.CharField(max_length=250, null=True)),
                ('rows', models.IntegerField(default=0)),
                ('processed_date', models.DateField(null=True)),
                ('firewall_rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.FirewallRule')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
