# Generated by Django 2.2.8 on 2020-02-18 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20200218_1747'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ThreatLogs',
            new_name='ThreatLog',
        ),
    ]
