# Generated by Django 2.2.5 on 2020-04-17 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20200226_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdFirewallRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Tenant')),
            ],
            options={
                'db_table': 'fh_prd_fw_rule_f',
            },
        ),
    ]
