# Generated by Django 2.2.5 on 2020-04-17 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_prodfirewallrule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProdFirewallRule',
        ),
    ]
