# Generated by Django 2.2.5 on 2020-04-17 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_delete_prodfirewallrule'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='firewallrule',
            table='fh_prd_fw_rule_f',
        ),
    ]
