# Generated by Django 2.2.5 on 2020-04-17 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20200417_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trafficlog',
            name='chart_engine_ran',
        ),
        migrations.RemoveField(
            model_name='trafficlog',
            name='db_engine_ran',
        ),
        migrations.RemoveField(
            model_name='trafficlog',
            name='dc_engine_ran',
        ),
        migrations.RemoveField(
            model_name='trafficlog',
            name='mis_engine_ran',
        ),
        migrations.RemoveField(
            model_name='trafficlog',
            name='ml_engine_ran',
        ),
        migrations.AlterModelTable(
            name='processedthreatlogdetail',
            table='fh_prd_thrt_log_dtl_f',
        ),
        migrations.AlterModelTable(
            name='processedtrafficlogdetail',
            table='fh_prd_trfc_log_dtl_f',
        ),
        migrations.AlterModelTable(
            name='threatlog',
            table='fh_prd_thrt_log_f',
        ),
        migrations.AlterModelTable(
            name='trafficlog',
            table='fh_prd_trfc_log_f',
        ),
        migrations.CreateModel(
            name='StageTrafficLogDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.CharField(max_length=250, null=True)),
                ('rows', models.IntegerField(default=0)),
                ('processed_date', models.DateField(null=True)),
                ('firewall_rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.FirewallRule')),
            ],
            options={
                'db_table': 'fh_stg_trfc_log_dtl_f',
            },
        ),
        migrations.CreateModel(
            name='StageThreatLogDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.CharField(max_length=250, null=True)),
                ('rows', models.IntegerField(default=0)),
                ('processed_date', models.DateField(null=True)),
                ('firewall_rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.FirewallRule')),
            ],
            options={
                'db_table': 'fh_stg_thrt_log_dtl_f',
            },
        ),
    ]
