# Generated by Django 2.2.5 on 2020-04-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20200417_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processedthreatlogdetail',
            name='processed_date',
        ),
        migrations.RemoveField(
            model_name='processedtrafficlogdetail',
            name='processed_date',
        ),
        migrations.RemoveField(
            model_name='stagethreatlogdetail',
            name='processed_date',
        ),
        migrations.RemoveField(
            model_name='stagetrafficlogdetail',
            name='processed_date',
        ),
        migrations.AddField(
            model_name='processedthreatlogdetail',
            name='processed_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='processedtrafficlogdetail',
            name='processed_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='stagethreatlogdetail',
            name='processed_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='stagetrafficlogdetail',
            name='processed_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='threatlog',
            name='processed_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trafficlog',
            name='processed_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
