# Generated by Django 2.2.5 on 2020-04-18 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20200418_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageTrafficLogDetailHourly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_datetime', models.DateTimeField()),
                ('threat_content_type', models.CharField(max_length=50, null=True)),
                ('source_address', models.CharField(max_length=50, null=True)),
                ('destination_address', models.CharField(max_length=50, null=True)),
                ('nat_source_ip', models.CharField(max_length=50, null=True)),
                ('nat_destination_ip', models.CharField(max_length=50, null=True)),
                ('destination_port', models.PositiveIntegerField()),
                ('nat_destination_port', models.PositiveIntegerField()),
                ('application', models.CharField(max_length=250, null=True)),
                ('protocol', models.CharField(max_length=50, null=True)),
                ('log_action', models.CharField(max_length=50, null=True)),
                ('source_zone', models.CharField(max_length=250, null=True)),
                ('destination_zone', models.CharField(max_length=250, null=True)),
                ('inbound_interface', models.CharField(max_length=250, null=True)),
                ('outbound_interface', models.CharField(max_length=250, null=True)),
                ('action', models.CharField(max_length=250, null=True)),
                ('category', models.CharField(max_length=250, null=True)),
                ('session_end_reason', models.CharField(max_length=250, null=True)),
                ('source_country', models.CharField(max_length=3, null=True)),
                ('destination_country', models.CharField(max_length=3, null=True)),
                ('device_name', models.CharField(max_length=3, null=True)),
                ('sum_bytes_sent', models.BigIntegerField()),
                ('sum_bytes_received', models.BigIntegerField()),
                ('avg_repeat_count', models.PositiveIntegerField()),
                ('sum_packets_received', models.BigIntegerField()),
                ('sum_packets_sent', models.BigIntegerField()),
                ('sum_time_elapsed', models.BigIntegerField()),
                ('firewall_rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firewall_rule_stage_traffic_log_detail_hourly', to='core.FirewallRule')),
                ('traffic_log', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.TrafficLog')),
            ],
            options={
                'db_table': 'fh_stg_prd_trfc_log_dtl_hr_a',
            },
        ),
        migrations.CreateModel(
            name='StageTrafficLogDetailDaily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_datetime', models.DateTimeField()),
                ('threat_content_type', models.CharField(max_length=50, null=True)),
                ('source_address', models.CharField(max_length=50, null=True)),
                ('destination_address', models.CharField(max_length=50, null=True)),
                ('nat_source_ip', models.CharField(max_length=50, null=True)),
                ('nat_destination_ip', models.CharField(max_length=50, null=True)),
                ('destination_port', models.PositiveIntegerField()),
                ('nat_destination_port', models.PositiveIntegerField()),
                ('application', models.CharField(max_length=250, null=True)),
                ('protocol', models.CharField(max_length=50, null=True)),
                ('log_action', models.CharField(max_length=50, null=True)),
                ('source_zone', models.CharField(max_length=250, null=True)),
                ('destination_zone', models.CharField(max_length=250, null=True)),
                ('inbound_interface', models.CharField(max_length=250, null=True)),
                ('outbound_interface', models.CharField(max_length=250, null=True)),
                ('action', models.CharField(max_length=250, null=True)),
                ('category', models.CharField(max_length=250, null=True)),
                ('session_end_reason', models.CharField(max_length=250, null=True)),
                ('source_country', models.CharField(max_length=3, null=True)),
                ('destination_country', models.CharField(max_length=3, null=True)),
                ('device_name', models.CharField(max_length=3, null=True)),
                ('sum_bytes_sent', models.BigIntegerField()),
                ('sum_bytes_received', models.BigIntegerField()),
                ('avg_repeat_count', models.PositiveIntegerField()),
                ('sum_packets_received', models.BigIntegerField()),
                ('sum_packets_sent', models.BigIntegerField()),
                ('sum_time_elapsed', models.BigIntegerField()),
                ('firewall_rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firewall_rule_stage_traffic_log_detail_daily', to='core.FirewallRule')),
                ('traffic_log', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.TrafficLog')),
            ],
            options={
                'db_table': 'fh_stg_prd_trfc_log_dtl_dy_a',
            },
        ),
    ]
