# Generated by Django 2.2.5 on 2020-04-18 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_stagetrafficlogdetaildaily_stagetrafficlogdetailhourly'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageThreatLogDetailEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_datetime', models.DateTimeField()),
                ('processed_datetime', models.DateTimeField()),
                ('log_name', models.CharField(max_length=500)),
                ('log_type', models.CharField(max_length=300, null=True)),
                ('threat_content_type', models.CharField(max_length=300, null=True)),
                ('config_version', models.CharField(max_length=300, null=True)),
                ('source_address', models.CharField(max_length=300, null=True)),
                ('destination_address', models.CharField(max_length=300, null=True)),
                ('nat_source_ip', models.CharField(max_length=300, null=True)),
                ('nat_destination_ip', models.CharField(max_length=300, null=True)),
                ('application', models.CharField(max_length=300, null=True)),
                ('virtual_system', models.CharField(max_length=300, null=True)),
                ('source_zone', models.CharField(max_length=300, null=True)),
                ('destination_zone', models.CharField(max_length=300, null=True)),
                ('inbound_interface', models.CharField(max_length=300, null=True)),
                ('outbound_interface', models.CharField(max_length=300, null=True)),
                ('log_action', models.CharField(max_length=300, null=True)),
                ('repeat_count', models.IntegerField(null=True)),
                ('source_port', models.IntegerField(null=True)),
                ('destination_port', models.IntegerField(null=True)),
                ('nat_source_port', models.IntegerField(null=True)),
                ('nat_destination_port', models.IntegerField(null=True)),
                ('flags', models.CharField(max_length=300, null=True)),
                ('protocol', models.CharField(max_length=300, null=True)),
                ('action', models.CharField(max_length=300, null=True)),
                ('url_filename', models.CharField(max_length=300, null=True)),
                ('threat_content_name', models.CharField(max_length=300, null=True)),
                ('category', models.CharField(max_length=300, null=True)),
                ('severity', models.CharField(max_length=300, null=True)),
                ('direction', models.CharField(max_length=300, null=True)),
                ('sequence_number', models.CharField(max_length=300, null=True)),
                ('action_flags', models.CharField(max_length=300, null=True)),
                ('source_country', models.CharField(max_length=300, null=True)),
                ('destination_country', models.CharField(max_length=300, null=True)),
                ('cpadding', models.CharField(max_length=300, null=True)),
                ('contenttype', models.CharField(max_length=300, null=True)),
                ('url_idx', models.CharField(max_length=300, null=True)),
                ('device_name', models.CharField(max_length=300, null=True)),
                ('file_url', models.CharField(max_length=300, null=True)),
                ('thr_category', models.CharField(max_length=300, null=True)),
                ('contentver', models.CharField(max_length=300, null=True)),
                ('sig_flags', models.CharField(max_length=300, null=True)),
                ('firewall_rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage_threat_log_firewall_rule_id', to='core.FirewallRule')),
            ],
            options={
                'db_table': 'fh_stg_thrt_log_dtl_evnt_f',
            },
        ),
    ]
