# Generated by Django 2.2.5 on 2020-04-18 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_stagethreatlogdetailevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagethreatlogdetailevent',
            name='traffic_log',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage_threat_log_traffic_log_id', to='core.TrafficLog'),
        ),
    ]
