# Generated by Django 2.2.5 on 2020-04-18 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_stagethreatlogdetailevent_traffic_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stagethreatlogdetailevent',
            name='traffic_log',
        ),
        migrations.AddField(
            model_name='stagethreatlogdetailevent',
            name='threat_log',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage_threat_log_traffic_log_id', to='core.ThreatLog'),
        ),
    ]
