# Generated by Django 2.2.5 on 2020-04-18 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20200418_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stagethreatlogdetailevent',
            name='processed_datetime',
        ),
    ]
