# Generated by Django 2.2.5 on 2020-04-18 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_remove_stagethreatlogdetailevent_processed_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stagethreatlogdetailevent',
            name='log_name',
        ),
    ]
