# Generated by Django 2.2.8 on 2020-05-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_threatlogdetailevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'fh_stg_trfc_appl_f',
            },
        ),
        migrations.CreateModel(
            name='StageProtocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'fh_stg_trfc_prot_f',
            },
        ),
        migrations.CreateModel(
            name='StageZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'fh_stg_trfc_zone_f',
            },
        ),
        migrations.AlterModelTable(
            name='application',
            table='fh_prd_trfc_appl_f',
        ),
        migrations.AlterModelTable(
            name='protocol',
            table='fh_prd_trfc_prot_f',
        ),
        migrations.AlterModelTable(
            name='sessionendreason',
            table='fh_prd_trfc_sess_end_f',
        ),
        migrations.AlterModelTable(
            name='zone',
            table='fh_prd_trfc_zone_f',
        ),
    ]
