# Generated by Django 2.2.8 on 2020-05-02 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20200502_2127'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='filter',
            table='fh_prd_trfc_fltr_f',
        ),
    ]
