# Generated by Django 2.2.8 on 2020-05-02 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20200502_2139'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='applicationchart',
            table='fh_prd_trfc_chrt_app_dt_hr_a',
        ),
        migrations.AlterModelTable(
            name='ipchart',
            table='fh_prd_trfc_chrt_ip_dt_hr_a',
        ),
        migrations.AlterModelTable(
            name='requestoriginchart',
            table='fh_prd_trfc_chrt_req_org_dt_hr_a',
        ),
        migrations.AlterModelTable(
            name='sankeychart',
            table='fh_prd_trfc_chrt_con_dt_hr_a',
        ),
        migrations.AlterModelTable(
            name='stagingfilter',
            table='fh_stg_trfc_fltr_f',
        ),
        migrations.AlterModelTable(
            name='timeserieschart',
            table='fh_prd_trfc_chrt_tm_srs_dt_hr_a',
        ),
        migrations.CreateModel(
            name='StageTimeSeriesChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bytes_sent', models.BigIntegerField()),
                ('bytes_received', models.BigIntegerField()),
                ('packets_sent', models.BigIntegerField()),
                ('packets_received', models.BigIntegerField()),
                ('count', models.BigIntegerField(default=0)),
                ('logged_datetime', models.DateTimeField()),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Filter')),
            ],
            options={
                'db_table': 'fh_stg_trfc_chrt_tm_srs_dt_hr_a',
            },
        ),
        migrations.CreateModel(
            name='StageSankeyChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bytes_sent', models.BigIntegerField()),
                ('bytes_received', models.BigIntegerField()),
                ('packets_sent', models.BigIntegerField()),
                ('packets_received', models.BigIntegerField()),
                ('count', models.BigIntegerField(default=0)),
                ('logged_datetime', models.DateTimeField()),
                ('source_ip', models.CharField(max_length=15)),
                ('destination_ip', models.CharField(max_length=15)),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Filter')),
            ],
            options={
                'db_table': 'fh_stg_trfc_chrt_con_dt_hr_a',
            },
        ),
        migrations.CreateModel(
            name='StageRequestOriginChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bytes_sent', models.BigIntegerField()),
                ('bytes_received', models.BigIntegerField()),
                ('packets_sent', models.BigIntegerField()),
                ('packets_received', models.BigIntegerField()),
                ('count', models.BigIntegerField(default=0)),
                ('country_name', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=10)),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Filter')),
            ],
            options={
                'db_table': 'fh_stg_trfc_chrt_req_org_dt_hr_a',
            },
        ),
        migrations.CreateModel(
            name='StageIPChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bytes_sent', models.BigIntegerField()),
                ('bytes_received', models.BigIntegerField()),
                ('packets_sent', models.BigIntegerField()),
                ('packets_received', models.BigIntegerField()),
                ('count', models.BigIntegerField(default=0)),
                ('logged_datetime', models.DateTimeField()),
                ('address', models.CharField(max_length=15)),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Filter')),
            ],
            options={
                'db_table': 'fh_stg_trfc_chrt_ip_dt_hr_a',
            },
        ),
        migrations.CreateModel(
            name='StageApplicationChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bytes_sent', models.BigIntegerField()),
                ('bytes_received', models.BigIntegerField()),
                ('packets_sent', models.BigIntegerField()),
                ('packets_received', models.BigIntegerField()),
                ('count', models.BigIntegerField(default=0)),
                ('logged_datetime', models.DateTimeField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Application')),
                ('firewall_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.FirewallRule')),
            ],
            options={
                'db_table': 'fh_stg_trfc_chrt_app_dt_hr_a',
            },
        ),
    ]
