# Generated by Django 2.2.8 on 2020-05-03 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20200502_2225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stagesankeychart',
            old_name='destination_ip',
            new_name='destination_address',
        ),
        migrations.RenameField(
            model_name='stagesankeychart',
            old_name='source_ip',
            new_name='source_address',
        ),
    ]
